// This file is auto-generated by scripts/generate-schemas.ts
// Do not edit this file manually.

import { Type as GeminiType } from '@google/genai';

export const textSpanSchema = {
  "type": "OBJECT",
  "properties": {
    "text": {
      "type": "STRING"
    },
    "style": {
      "type": "OBJECT",
      "properties": {
        "fontFamily": {
          "type": "STRING"
        },
        "fontSize": {
          "type": "NUMBER"
        },
        "fontWeight": {
          "type": "NUMBER"
        },
        "color": {
          "type": "STRING"
        },
        "letterSpacing": {
          "type": "NUMBER"
        },
        "textShadow": {
          "type": "STRING"
        },
        "textStroke": {
          "type": "STRING"
        },
        "minFontSize": {
          "type": "NUMBER"
        },
        "maxFontSize": {
          "type": "NUMBER"
        }
      }
    }
  },
  "required": [
    "text",
    "style"
  ]
};

export const textSectionSchema = {
  "type": "STRING",
  "description": "Unsupported type: import(\"/Users/chengyizhen/Develop/Github/ai-creative-assistant (44)/types\").TextSection"
};

export const imageSectionSchema = {
  "type": "STRING",
  "description": "Unsupported type: import(\"/Users/chengyizhen/Develop/Github/ai-creative-assistant (44)/types\").ImageSection"
};

export const layoutBoxSchema = {
  "type": "OBJECT",
  "properties": {
    "id": {
      "type": "STRING"
    },
    "type": {
      "type": "STRING"
    },
    "role": {
      "type": "STRING"
    },
    "constraints": {
      "type": "OBJECT",
      "properties": {
        "top": {
          "type": "STRING"
        },
        "bottom": {
          "type": "STRING"
        },
        "left": {
          "type": "STRING"
        },
        "right": {
          "type": "STRING"
        },
        "width": {
          "type": "STRING"
        },
        "height": {
          "type": "STRING"
        },
        "centerX": {
          "type": "STRING"
        },
        "centerY": {
          "type": "STRING"
        }
      }
    },
    "anchor": {
      "type": "OBJECT",
      "properties": {
        "elementId": {
          "type": "STRING"
        },
        "originPoint": {
          "type": "STRING",
          "enum": [
            "top-left",
            "top-center",
            "top-right",
            "center-left",
            "center",
            "center-right",
            "bottom-left",
            "bottom-center",
            "bottom-right"
          ]
        },
        "offset": {
          "type": "OBJECT",
          "properties": {
            "x": {
              "type": "NUMBER"
            },
            "y": {
              "type": "NUMBER"
            }
          },
          "required": [
            "x",
            "y"
          ]
        },
        "attachmentMode": {
          "type": "STRING",
          "enum": [
            "outside",
            "inside"
          ]
        }
      },
      "required": [
        "elementId",
        "originPoint",
        "offset"
      ]
    },
    "backgroundColor": {
      "type": "STRING"
    },
    "backgroundImage": {
      "type": "STRING"
    },
    "borderRadius": {
      "type": "NUMBER"
    },
    "paddingTop": {
      "type": "NUMBER"
    },
    "paddingRight": {
      "type": "NUMBER"
    },
    "paddingBottom": {
      "type": "NUMBER"
    },
    "paddingLeft": {
      "type": "NUMBER"
    },
    "sections": {
      "type": "ARRAY",
      "items": {
        "type": "OBJECT",
        "description": "Could be one of multiple object types."
      }
    },
    "layoutMode": {
      "type": "STRING",
      "enum": [
        "flex",
        "grid"
      ]
    },
    "zIndex": {
      "type": "NUMBER"
    },
    "flexDirection": {
      "type": "STRING",
      "enum": [
        "row",
        "column"
      ]
    },
    "justifyContent": {
      "type": "STRING",
      "enum": [
        "center",
        "flex-start",
        "flex-end",
        "space-between",
        "space-around"
      ]
    },
    "alignItems": {
      "type": "STRING",
      "enum": [
        "center",
        "flex-start",
        "flex-end",
        "stretch"
      ]
    },
    "gridTemplateColumns": {
      "type": "STRING"
    },
    "gridTemplateRows": {
      "type": "STRING"
    },
    "columnGap": {
      "type": "NUMBER"
    },
    "rowGap": {
      "type": "NUMBER"
    },
    "rotation": {
      "type": "NUMBER"
    },
    "marginTop": {
      "type": "NUMBER"
    },
    "marginBottom": {
      "type": "NUMBER"
    },
    "importance": {
      "type": "STRING",
      "enum": [
        "required",
        "optional",
        "recommended"
      ]
    },
    "aiInstructions": {
      "type": "STRING"
    },
    "isContentLocked": {
      "type": "BOOLEAN"
    },
    "isVisible": {
      "type": "BOOLEAN"
    },
    "isLocked": {
      "type": "BOOLEAN"
    },
    "flexGrow": {
      "type": "NUMBER"
    },
    "flexShrink": {
      "type": "NUMBER"
    },
    "gridColumn": {
      "type": "STRING"
    },
    "gridRow": {
      "type": "STRING"
    }
  },
  "required": [
    "id",
    "type",
    "role",
    "constraints",
    "backgroundColor",
    "backgroundImage",
    "borderRadius",
    "paddingTop",
    "paddingRight",
    "paddingBottom",
    "paddingLeft",
    "sections",
    "layoutMode"
  ]
};

